// vue/src/app/Form.vue
<template>
  <form
    class="flex items-stretch"
    @submit.prevent="onsubmit"
    autocomplete="off"
  >
    <label for="title" class="self-center font-bold">
      New:
    </label>
    <input
      type="text"
      name="title"
      id="title"
      class="appearance-none border rounded rounded-r-none w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline ml-2"
      v-model="value"
      autocomplete="off"
    />
    <button
      type="submit"
      class="font-bold rounded rounded-l-none text-white px-4 hover:bg-blue-700 bg-blue-800 text-center no-underline block focus:shadow-outline focus:outline-none"
    >
      Add
    </button>
  </form>
</template>
<script>
export default {
  props: {
    itemsAdd: Function,
  },
  data() {
    const params = new URL(window.location).searchParams;
    const v = [
      ...(params.get('title') ? [params.get('title')] : []),
      ...(params.get('text') ? [params.get('text')] : []),
      ...(params.get('url') ? [params.get('url')] : []),
    ];

    return {
      value: v.join(' - '),
    };
  },
  methods: {
    onsubmit: function(e) {
      if (this.value !== '') {
        this.itemsAdd(this.value);
        this.$el.querySelector('[name=title]').focus();
        this.value = '';
      }
    },
  },
};
</script>

// src/app/Form.jsx
import { h } from 'preact';
import { useRef } from 'preact/hooks';

const Form = ({ className = '', itemsAdd }) => {
  const input = useRef(null);

  return (
    <form
      className={`flex items-stretch ${className}`}
      onSubmit={e => {
        e.preventDefault();
        if (input.current.value !== '') {
          itemsAdd(input.current.value);
          input.current.value = '';
        }
      }}
    >
      <label htmlFor="title" className="self-center font-bold">
        New:
      </label>
      <input
        type="text"
        name="title"
        id="title"
        className="appearance-none border rounded rounded-r-none w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline ml-2"
        ref={input}
      />
      <button
        type="submit"
        className="font-bold rounded rounded-l-none text-white px-4 hover:bg-blue-700 bg-blue-500 text-center no-underline block"
      >
        Add
      </button>
    </form>
  );
};

export default Form;
